name: OraxenMythicMobsIntegration
main: cn.leomc.OraxenMythicMobsIntegration.OraxenMythicMobsIntegration
version: 3.0
author: LeoMC
api-version: 1.14
description: Oraxen MythicMobs Integration
depend:
  - MythicMobs
  - Oraxen